# Exercise 1: Try Linear Regression just using numpy (Without Tensorflow/Pytorch or other torch library). 

In [ ]:
import numpy as np

In [ ]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [ ]:
# Target (apples)
targets = np.array([[56], 
                    [81], 
                    [119], 
                    [22], 
                    [103]], dtype='float32')

In [ ]:
print("Inputs:",inputs)
print("Targets:",targets)

Inputs: [[ 73.  67.  43.]
 [ 91.  88.  64.]
 [ 87. 134.  58.]
 [102.  43.  37.]
 [ 69.  96.  70.]]
Targets: [[ 56.]
 [ 81.]
 [119.]
 [ 22.]
 [103.]]


In [ ]:
from numpy import random

w = random.rand(1, 3)
b=random.rand(1,1)
print(w)
print(b)

[[0.00535657 0.3576928  0.27095887]]
[[0.98186623]]


In [ ]:
# Define the model
# @=FOR DOT PRODUCT
def model(x):
    return x @ w.transpose()+b

In [ ]:
# Generate predictions
pred=model(inputs)
print(pred)

[[36.98954494]
 [50.28764826]
 [65.09433768]
 [26.93450507]
 [54.65709929]]


In [ ]:
# Compare with targets
print(targets)

[[ 56.]
 [ 81.]
 [119.]
 [ 22.]
 [103.]]


## Loss Function

We can compare the predictions with the actual targets, using the following method: 
* Calculate the difference between the two matrices (`preds` and `targets`).
* Square all elements of the difference matrix to remove negative values.
* Calculate the average of the elements in the resulting matrix.

The result is a single number, known as the **mean squared error** (MSE).

In [ ]:
# MSE loss
def mse(t1,t2):
    diff=(t1-t2)**2
    _sum_=np.sum(diff)   
    return _sum_/diff.size


In [ ]:
# Compute loss
loss=mse(pred,targets)
print(loss)
l_rate=1e-4

1314.3703541168882


## Gradient Descent Algorithm

In [ ]:
def grad_desc(w,b):
    m=len(targets)
    b_de=(l_rate * ((1/m) * np.sum(model(inputs) - targets)))
    for i in range(len(w)):
        w_de=(l_rate * ((1/m) * np.sum(model(inputs) - targets)))
    return w_de,b_de

## Training for 200 epochs

In [ ]:
# Train for 200 epochs
for i in range(200):
    pred=model(inputs)
    loss=mse(pred,targets)
    w_de,b_de=grad_desc(w,b)
    w=w-w_de
    b=b-b_de

In [ ]:
print(model(inputs)) 

[[ 60.99553615]
 [ 82.12168008]
 [101.62519387]
 [ 50.81002894]
 [ 85.44739237]]


In [ ]:
print(targets)

[[ 56.]
 [ 81.]
 [119.]
 [ 22.]
 [103.]]


In [ ]:
loss=mse(pred,targets)
print(loss)

293.241851057183
